version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: empladoscontainer
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: empleados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuariopassword
      MYSQL_SSL_CA: ""
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
